#ifndef TREE_ERRORS_H
#define TREE_ERRORS_H

#include <stdio.h>
#include <stdlib.h>

typedef enum {
    ERR_NONE = 0,

    // 100. ERRORES DE SISTEMA / MEMORIA (FATALES)
    ERR_SYS_START = 100,
    ERR_SYS_NULL_NODETYPE,
    ERR_SYS_NO_MEM_AST,
    ERR_SYS_NO_MEM_FLOW,
    ERR_SYS_NO_MEM_MEMORY,
    ERR_SYS_NULL_POINTER,
    ERR_SYS_OVERFLOW_SYMTAB,

    // 200. ERRORES SEMÁNTICOS (ANÁLISIS DE TIPOS)
    ERR_SEM_START = 200,
    ERR_SEM_UNINITIALIZED_VAR,
    ERR_SEM_NUMBERS_ONLY,
    ERR_SEM_TYPE_MISMATCH,
    ERR_SEM_INVALID_FLOW_COND,
    ERR_SEM_ARG_COUNT_MISMATCH,

    // 300. ERRORES DE COLECCIONES (LISTAS Y SETS)
    ERR_COL_START = 300,
    ERR_COL_INDEX_OUT_OF_BOUNDS,
    ERR_COL_EXPECTED_INT,
    ERR_COL_EXPECTED_LIST,
    ERR_COL_EXPECTED_SET,
    ERR_COL_CANNOT_CONCAT,

    // 400. ERRORES DE RUNTIME / EJECUCIÓN GENERAL
    ERR_RUN_START = 400,
    ERR_RUN_GENERIC_EXECUTION,
    ERR_RUN_DIVISION_BY_ZERO,
    ERR_GENERAL
} TreeErrorCode;

void tree_notify(TreeErrorCode code, const char* extra_info);

#endif
